### ISSUE TITLE
readme.md: dependencies and OS version

### ISSUE THREAD

**Issue by viktoriasee** [tsenger/CCU2F#5]
Hi Tobias
I would like to experiment with a FIDO U2F card without being a real programmer. Can you explain a little further where to get/buy the dependencies `com.nxp.id.jcopx.KeyAgreementX` and `com.nxp.id.jcopx.KeyBuilderX`? If they are included in newer Javacards, how do I determine the version and how do I get it from the card to the project? Any chance to get a binary?

**Comment by tsenger** [comment]
You can try to get the cards and libraries directly via NXP or a card seller which can provide you access to the libraries. Normally you have to sign an NDA with NXP for this.
So I can't help with this, sorry.
As mentioned in the README.md newer cards might have the `KeyAgreement.ALG_EC_SVDP_DH_PLAIN_XY` class included. So if your card supports this you can easily change `com.nxp.id.jcopx.KeyAgreementX.ALG_EC_SVDP_DH_PLAIN_XY` to this class.
